spring.application.name=ecotrack-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/ecotrack
spring.datasource.username=fahadfurquan
spring.datasource.password=ecotrack123

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

# JWT Configuration (86400000 = 24 hours in ms)
security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
security.jwt.expiration-time=86400000

# Cloudinary Configuration
cloudinary.cloud-name=ddszr1sdv
cloudinary.api-key=439172672988712
cloudinary.api-secret=ivDQR-Ao72Mc0TQV1ObcyktN4RA